[theme]
primaryColor="#003c6f"
backgroundColor="#000000"
secondaryBackgroundColor="#000020"
textColor="white"
font="sans serif"

[browser]
gatherUsageStats = false

[deprecation]
showPyplotGlobalUse = false